### ISSUE TITLE
Code snippet measures integer operations, text mentions floating point operations. 

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#101]
https://github.com/algorithmica-org/algorithmica/blob/990b6b1134da1c4b5ab1bb85e741f20f4cedad69/content/english/hpc/cpu-cache/bandwidth.md?plain=1#L30

Not sure if the meaning of FLOPS has been extended in practice, or integer op throughput is tightly coupled to flops.

**Comment by sslotin** [comment]
It's an issue that needs to be fixed worldwide, not just in this book. People use GFLOPS to refer to anything. There is a more general GOPS term, but it sounds ridiculous.
