### ISSUE TITLE
Assembly Language

### ISSUE THREAD

**Issue by Narann** [algorithmica-org/algorithmica#106]
Hello. I suspect some information are missing from the page: https://en.algorithmica.org/hpc/architecture/assembly/

> For comparison, here is what the summation loop looks like in AT&T asm

But there is no loop in the page, the example is `*c = *a + *b`.

Good luck, keep the good work! :)

EDIT: What I mean because it hasn't been explained before, the example is confusing as you don't know what the original code is supposed to do, and so, don't understand the AT&T assembly code.

EDIT2: OK, the for loop you are talking about is on the next page (loops and conditionals) and directly in assembly. Here is my suggestion: Stay on the original example in Assembly Language page (means `*c = *a + *b`) and provide a C example at the beginning of the "Loops and Conditionals" page. I think this would be more clear.

Keep the good work! :)

**Comment by sslotin** [comment]
Yeah, some time ago I rearranged the content of that chapter and forgot that the example is for the loop. Changed it to `a + b`. Thanks for reporting!
