### ISSUE TITLE
Feedback on fast sqrt

### ISSUE THREAD

**Issue by SUPERCILEX** [algorithmica-org/algorithmica#119]
https://github.com/algorithmica-org/algorithmica/blob/master/content/english/hpc/arithmetic/rsqrt.md

Above the graph, I think there's a typo: instead of `L = 23`, it should say `L = 2^23`. It would be nice to also mention that a multiplication by a power of two is equivalent to a left shift (hence where the `I_x` bit pattern comes from). The bias also comes out of nowhere: it should be briefly explained that IEEE exponents are shifted by 2^(e_x-1)-1. It's also be nice to have labels on the graph axes as I'm still not 100% sure what they mean. I believe vertical=binary representation while horizontal=float number.

**Comment by sslotin** [comment]
Thanks, clarified all that.

**Comment by SUPERCILEX** [comment]
Awesome!
