### ISSUE TITLE
Website hotkeys conflict with browser hotkeys

### ISSUE THREAD

**Issue by tm-a-t** [algorithmica-org/algorithmica#40]
In most browsers `Alt + Left arrow` and `Alt + Right arrow` are used to go back and forward in page history.

These hotkeys don't work on Algorithmica. They are mixed up with `Left arrow` and `Right arrow` (navigation between pages).

**Comment by sslotin** [comment]
[Fixed](https://github.com/algorithmica-org/algorithmica/commit/12d25fde1cc733ae3e04cba91f2824125de675ca), thanks for pointing it out.
