### ISSUE TITLE
Found the random search limit

### ISSUE THREAD

**Issue by mlochbaum** [algorithmica-org/algorithmica#57]
The slowdown for randomized binary search versus the normal version is `2*log(2)`, about 1.386. Doesn't require much calculus in the end: the randomized time simplifies to twice the harmonic series, which has the well-known sum `log(n) + O(1)`. Dividing by `log2(n)` causes the `O(1)` part to go to 0 (slowly), and `log(n) / log2(n)` is the constant `log(2)`.

Flattening the recurrence, starting from your linear-time version:

```python
# From random-binsearch.py
g[k] = (s[k - 1] * 2 / k / (k - 1) + 1) * k
     = 2 * s[k - 1] / (k - 1) + k
s[k] = s[k - 1] + g[k]

# Substitute g
s[k] = s[k - 1] * (1 + 2 / (k - 1)) + k
     = s[k - 1] * (k + 1) / (k - 1) + k
(s[k] / k) = s[k - 1] * (1 + 1 / k) / (k - 1) + 1
# Define r
r[k] = s[k] / k
r[k] = r[k - 1] * (1 + 1 / k) + 1

# Rewrite original g recurrence in f and r
f[k] * k = 2 * r[k - 1] + k
r[k - 1] = (f[k] - 1) * k / 2

# Substitute into r recurrence
(f[k + 1] - 1) * (k + 1) / 2 = (f[k] - 1) * k / 2 * (1 + 1 / k) + 1
                             = (f[k] - 1) * (k + 1) / 2 + 1
(f[k + 1] - 1) = (f[k] - 1) + 2 / (k + 1)
f[k + 1] = f[k] + 2 / (k + 1)
f[k] = f[k - 1] + 2 / k
```

**Comment by sslotin** [comment]
Great, thanks! People don't often contribute to unpublished posts :smile:

Added to the article https://github.com/algorithmica-org/algorithmica/commit/c5ef9af616083eb4cb989da7a95741584af45797. For some reason, it looks way more complicated when typed in TeX.

**Comment by mlochbaum** [comment]
You had some links to it in the branchless programming section, so I searched the repository to find it.

**Comment by sslotin** [comment]
My reluctance to implement an internal link checker paid off then.
