### ISSUE TITLE
Right-shift 31 formula in section 3.3 is not always correct

### ISSUE THREAD

**Issue by chrchang** [algorithmica-org/algorithmica#64]
"(a[i] - 50) >> 31" is equivalent to (a[i] < 50) for most possible values of a[i]... but not the ones in [-2^31, 50 - 2^31).  So this is not a valid optimization unless the compiler can prove that all a[i] are not smaller than 50 - 2^31.

**Comment by sslotin** [comment]
Added a note about it, thanks.
