### ISSUE TITLE
"mul  eax, ebx" in section 3.3 is not the correct usage of "mul"

### ISSUE THREAD

**Issue by song-jx** [algorithmica-org/algorithmica#66]
https://en.algorithmica.org/hpc/pipelining/branchless/#:~:text=31%20%20%20%20%3B%20t%20%3E%3E%3D%2031-,mul%20%20eax%2C%20ebx,-%3B%20x%20*%3D%20t

The mul instruction looks like "mul reg/mem", has only one operand, should be changed to "mul ebx" or "imul eax, ebx".

**Comment by sslotin** [comment]
Fixed, thanks.
