### ISSUE TITLE
404 error for link contained in 3. Instruction-Level Parallelism

### ISSUE THREAD

**Issue by rjurga** [algorithmica-org/algorithmica#75]
In the intro to chapter 3, there is a link to https://en.algorithmica.org/hpc/pipelining/scheduling which gives a 404.
I see the `scheduling` page in the repo, but on the website that page does not appear in the sidebar.

**Comment by sslotin** [comment]
Thanks, removed the link (I don't want to finish the instruction scheduling section right now).

Damn, I really need to implement an internal link checker…
