### ISSUE TITLE
Time estimation formulae is incorrect in Complexity Models

### ISSUE THREAD

**Issue by kaedon-pargo** [algorithmica-org/algorithmica#81]
`To estimate the real running time of a program, you need to sum all latencies for its executed instructions and multiply it by the clock frequency, that is, the number of cycles a particular CPU does per second.`  
This would mean that a higher clock frequency would cause the program to take longer to run rather than be quicker. This should rather be sum of latencies divided by clock frequency. Dimensionally, cycles * (cycles/second) gives us cycles^2/second whereas cycles * (seconds/cycles) gives us seconds.

**Comment by sslotin** [comment]
You're right, fixed it.
