### ISSUE TITLE
Typo in https://github.com/algorithmica-org/algorithmica/blob/master/content/english/hpc/data-structures/segment-trees.md: "fo"

### ISSUE THREAD

**Issue by tv42** [algorithmica-org/algorithmica#85]
> In this case, the Fenwick tree is not equivalent to a segment tree **fo** size

**Comment by sslotin** [comment]
Fixed.

Can you maybe edit pages directly on GitHub if Prose isn't working? Not a huge difference, but it would save me some time.

**Comment by tv42** [comment]
I promise to not find any more typos -- I skimmed everything I intended to skim ;)
