### ISSUE TITLE
Intervall Inclusion Statement untrue

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#87]
https://github.com/algorithmica-org/algorithmica/blob/702eed738c2dba7e18665ec9262a854e939ace02/content/english/hpc/arithmetic/float.md?plain=1#L120

Since [0,1] is included in [0,infinity), even for floats, this statement cannot be true.

**Comment by sslotin** [comment]
Thanks for noticing. I meant [0, 1] has roughly as many numbers as [1, infinity).
