### ISSUE TITLE
Consider using passive voice

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#89]
https://github.com/algorithmica-org/algorithmica/blob/702eed738c2dba7e18665ec9262a854e939ace02/content/english/hpc/arithmetic/ieee-754.md?plain=1#L28

The sentence reads a little weird to me. I’m not a native English speaker though.

**Comment by sslotin** [comment]
Indeed. Changed to:

> One of the reasons why they are stored in this exact order is that it is easier to compare and sort them: you can use mostly the same comparator circuit as for [unsigned integers](http://localhost:1313/hpc/arithmetic/integer), except for maybe flipping some bits in case one of the numbers is negative.
