### ISSUE TITLE
Statement not strictly true

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#93]
https://github.com/algorithmica-org/algorithmica/blob/702eed738c2dba7e18665ec9262a854e939ace02/content/english/hpc/arithmetic/errors.md?plain=1#L27

With real numbers, precisely addition and multiplication are associative and commutative. In contrast this is not the case for floating point numbers, and thus by extension not for the rounding error of these operations. 

At least to me, this is quite unintuitive and an further explanation would be greatly appreciated.

**Comment by sslotin** [comment]
Rewrote that section.
