### ISSUE TITLE
Better by which benchmark.

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#94]
https://github.com/algorithmica-org/algorithmica/blob/702eed738c2dba7e18665ec9262a854e939ace02/content/english/hpc/arithmetic/errors.md?plain=1#L44

Not a very compelling reason to why changing rounding mode is preferable to changing precision.

**Comment by sslotin** [comment]
> This test is **often** better than switching all computations to lower precision and checking whether the result changed by too much because the default round-to-nearest policy converges to the correct “expected” value given enough averaging: half of the time the errors are rounding up, and the other they are rounding down — so, statistically, they cancel each other.
