### ISSUE TITLE
Condition and stability are intrinsically different.

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#95]
https://github.com/algorithmica-org/algorithmica/blob/702eed738c2dba7e18665ec9262a854e939ace02/content/english/hpc/arithmetic/errors.md?plain=1#L78

 Condition is a property of the problem at hand, stability is a property of an algorithm used to solve it. An algorithm solving a problem can be stable only if the underlying problem is well-conditioned. On the other hand, even if a problem is well conditioned, an algorithm solving it may be unstable (A classic example is matrix inversion). This is important because the remedy to bad conditioning is modifying the problem, whereas if your algorithm suffers from instability, it’s finding another algorithm.

**Comment by sslotin** [comment]
Corrected the definition (I probably need more formalism in that section).
