### ISSUE TITLE
Self contradiction

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#96]
https://github.com/algorithmica-org/algorithmica/blob/702eed738c2dba7e18665ec9262a854e939ace02/content/english/hpc/arithmetic/errors.md?plain=1#L171

You are contradicting yourself. On the one hand, you say switching to higher precision  is not scalable, on the other hand, that’s what you recommend here.

**Comment by sslotin** [comment]
Poor choice of words. I meant that for other types of problems, you should switch to larger types, use double-double arithmetic, etc. The Kahan summation algorithm is just for summation.
