### ISSUE TITLE
Newton is probably not the basis for more than 50% of optimization algorithms.

### ISSUE THREAD

**Issue by AlexanderNenninger** [algorithmica-org/algorithmica#98]
https://github.com/algorithmica-org/algorithmica/blob/702eed738c2dba7e18665ec9262a854e939ace02/content/english/hpc/arithmetic/newton.md?plain=1#L36

Differentiability is a very strong assumption. Although Newton’s method is widely used, there are so many optimization methods, that this statement seems improbable.

**Comment by AlexanderNenninger** [comment]
Hopefully my feedback doesn't seem to harsh. I really enjoyed reading Algorithmica so far.

**Comment by sslotin** [comment]
No, on the contrary — thanks very much for the suggestions, and please keep them coming. I just haven't replied to them because I've been busy due to the war and stuff.

**Comment by AlexanderNenninger** [comment]
Yeah, war always sucks. It's sad to have so little control over such important matters.

**Comment by sslotin** [comment]
> Newton’s method is very important: it is the basis of a **wide range** of optimization solvers in science and engineering.
